### ISSUE TITLE
The results for MeCo and MeCo_opt on NATS-Bench-201 SSS

### ISSUE THREAD

**Issue by hosytuyen** [HamsterMimi/MeCo#1]
Hi, thank your for the great work!

Regarding the results for MeCo and MeCo_opt with on NATS-Bench-201 SSS, I have tried to reproduce the results and have a few questions:

1. Reproduce NAS-Bench-201 SSS

- Despite the code in `correlation/NAS_Bench_201.py` provides with the option for SSS search space, I do not manage to run SSS search space. 
- Which API that you use for SSS search space? The current API in your code (i.e. [nas_201_bench](https://github.com/D-X-Y/NAS-Bench-201/tree/master)) seems not to support SSS. 
- I have tried to use a [common API](https://github.com/D-X-Y/NATS-Bench) to compute MeCo. The results look comparable to the results in the paper expect for the CIFAR100 (highlighted in red). May I ask for your suggestion for this?

2. The implementation for MeCo_opt

The idea for MeCo_opt is interesting.
It seems that the current public source code does not include MeCo_opt.
I have tried to implement it by following the description in the paper (n=8 and adding channel weight).
Unfortunately, the results are not reproducible (highlighted in green).
May I ask for the MeCo_opt source code and some suggestions for the MeCo_opt reproduction?

<img width="628" alt="Screenshot 2024-01-08 at 2 24 55 AM" src="https://github.com/HamsterMimi/MeCo/assets/32817741/d23e6bc6-4c06-47ed-b543-054da4a6a130">

Thank you for your time. Looking forward to your response.

**Comment by HamsterMimi** [comment]
I’m sorry for replying so late. We also use the common API to compute MeCo. We update and rerun the code and the results for sss are provided in ./correlation/result now.

**Comment by HamsterMimi** [comment]
If you have any more questions, feel free to email me.
